### ISSUE TITLE
ImportError: No module named callbacks

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen-vm#168]
Hi All, 
Im installing bcbio_vm on a google instance.  Everthing installed cleanly.  Then I ran 
bcbio_vm.py install --wrapper
and that finished cleanly.

but now im getting the following error:

patrickjenningsreed@bcbio-1:~$ bcbio_vm.py
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/home/patrickjenningsreed/install/bcbio-vm/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py",
 line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/patrickjenningsreed/install/bcbio-vm/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py",
 line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/home/patrickjenningsreed/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py
2.7.egg/EGG-INFO/scripts/bcbio_vm.py", line 27, in <module>
    
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/cluster.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/bootstrap.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/bcbiovm/aws/common.py", line 9, in <module>
ImportError: No module named callbacks

**Comment by chapmanb** [comment]
Patrick;
Apologies about the issue with this. I dug into the problem and it looks like the latest version of conda is extra aggressive with dependency upgrades and results in downgrading the bcbio-nextgen-vm package due to a pin, causing the error from the old version. I pushed a fix and will update the bioconda package with this to avoid it in the future, but you can fix your version now with:
```
bcbiovm_conda install -c conda-forge -c bioconda bcbio-nextgen-vm bcbio-nextgen cwltool arvados-cwl-runner toil  rabix-bunny
```
and then a second time after the new bioconda package gets built tomorrow to be future proof for new `--wrapper` updates. Sorry again about the issue and thanks for the detailed report to track it down.

**Comment by PatrickJReed** [comment]
Thanks for the quick response Brad.  Im going to close [https://github.com/bcbio/bcbio-nextgen/issues/2353](url) under the assumption that bcbio_vm is the best way to go on google cloud.  Cheers.
