### ISSUE TITLE
docker image ModuleNotFoundError

### ISSUE THREAD

**Issue by ltnetcase** [bcbio/bcbio-nextgen-vm#192]
When I try to install bcbio-nextgen-vm with fresh install, I got the following error (run again the same command):

>$ bcbio_vm.py --datadir=/GeneCloud001/sysadmin/bcbio-data install --data --tools --genomes GRCh37 --aligners bwa --core 10
>Retrieving bcbio-nextgen docker image with code and tools
>Using default tag: latest
>Trying to pull repository quay.io/bcbio/bcbio-vc ...
>latest: Pulling from quay.io/bcbio/bcbio-vc
>Digest: sha256:cc44e242be9875bea6542b706033897279aa4301cf4800d25de8bb2e51e57bdc
>Status: Image is up to date for quay.io/bcbio/bcbio-vc:latest
>[2020-10-28T02:58Z] DEBUG: Running in docker container: d4d571b2164bb9342782397f2bce4116f49aadfa29ec8a07d9bc4136d6340029
>[2020-10-28T02:58Z] DEBUG: docker attach --no-stdin d4d571b2164bb9342782397f2bce4116f49aadfa29ec8a07d9bc4136d6340029
>[2020-10-28T02:58Z] DEBUG: Traceback (most recent call last):
>[2020-10-28T02:58Z] DEBUG:   File "/usr/local/bin/bcbio_nextgen.py", line 34, in <module>
>[2020-10-28T02:58Z] DEBUG:     from bcbio.setpath import prepend_bcbiopath
>[2020-10-28T02:58Z] DEBUG: ModuleNotFoundError: No module named 'bcbio'
>[2020-10-28T02:58Z] ERROR: Uncaught exception occurred
>Traceback (most recent call last):
>  File "/usr/local/opt/anaconda/envs/bcbio/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
>    _do_run(cmd, checks, log_stdout, env=env)
>  File "/usr/local/opt/anaconda/envs/bcbio/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
>    raise subprocess.CalledProcessError(exitcode, error_msg)
>subprocess.CalledProcessError: Command 'docker attach --no-stdin d4d571b2164bb9342782397f2bce4116f49aadfa29ec8a07d9bc4136d6340029
>Traceback (most recent call last):
>  File "/usr/local/bin/bcbio_nextgen.py", line 34, in <module>
>    from bcbio.setpath import prepend_bcbiopath
>ModuleNotFoundError: No module named 'bcbio'
>' returned non-zero exit status 1.
>Stopping docker container
>Traceback (most recent call last):
>  File "/usr/local/opt/anaconda/envs/bcbio/bin/bcbio_vm.py", line 354, in <module>
>    args.func(args)
>  File "/usr/local/opt/anaconda/envs/bcbio/bin/bcbio_vm.py", line 40, in cmd_install
>    install.full(args, devel.DOCKER)
>  File "/usr/local/opt/anaconda/envs/bcbio/lib/python3.7/site-packages/bcbiovm/docker/install.py", line 29, in full
>    manage.run_bcbio_cmd(args.image, dmounts, ["upgrade"])
>  File "/usr/local/opt/anaconda/envs/bcbio/lib/python3.7/site-packages/bcbiovm/docker/manage.py", line 48, in run_bcbio_cmd
>    raise e
>  File "/usr/local/opt/anaconda/envs/bcbio/lib/python3.7/site-packages/bcbiovm/docker/manage.py", line 44, in run_bcbio_cmd
>    log_stdout=True)
>  File "/usr/local/opt/anaconda/envs/bcbio/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
>    _do_run(cmd, checks, log_stdout, env=env)
>  File "/usr/local/opt/anaconda/envs/bcbio/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
>    raise subprocess.CalledProcessError(exitcode, error_msg)
>subprocess.CalledProcessError: Command 'docker attach --no-stdin d4d571b2164bb9342782397f2bce4116f49aadfa29ec8a07d9bc4136d6340029
>Traceback (most recent call last):
>  File "/usr/local/bin/bcbio_nextgen.py", line 34, in <module>
>    from bcbio.setpath import prepend_bcbiopath
>ModuleNotFoundError: No module named 'bcbio'

Can anyone help to fix this issue? It seems like an old issue [here](https://github.com/bcbio/bcbio-nextgen/issues/2740)

**Comment by hackdna** [comment]
More information here: https://github.com/bcbio/bcbio_docker/issues/4
